"""Agrega campo real_hours a Task

Revision ID: 004383151d41
Revises: e3580edf8960
Create Date: 2025-04-24 15:02:21.506102

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '004383151d41'
down_revision = 'e3580edf8960'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('real_hours', sa.Float(), nullable=True))
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.alter_column('assigned_to_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('real_hours')

    # ### end Alembic commands ###
