"""Crear tabla ProjectLog para bitácora

Revision ID: e16ffa38390e
Revises: e30f3c43d701
Create Date: 2025-04-20 01:04:40.564564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e16ffa38390e'
down_revision = 'e30f3c43d701'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('archivo_adjunto', sa.String(length=255), nullable=True),
    sa.Column('tipo_evento', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['project.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project_log')
    # ### end Alembic commands ###
