"""Agregar campos status y admin_comment al proyecto

Revision ID: e30f3c43d701
Revises: c0e83e370cf2
Create Date: 2025-04-19 23:54:32.610622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e30f3c43d701'
down_revision = 'c0e83e370cf2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('admin_comment', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('admin_comment')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
