"""Fix backref conflict

Revision ID: eb57a234ac97
Revises: 18a5e0d6f2e6
Create Date: 2025-01-12 15:03:16.697938

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb57a234ac97'
down_revision = '18a5e0d6f2e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estimated_time', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('estimated_time')

    # ### end Alembic commands ###
